version: '3.8'

services:
  salon-service:
    build:
      context: .
      dockerfile: Dockerfile.salon-service
    ports:
      - "8081:8081"
    environment:
      - SALON_SERVICE_ENV=production
      - SALON_SERVICE_DB_URL=${SALON_DB_URL}
      - SALON_SERVICE_JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - SALON_SERVICE_JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user-service
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_ENV=production
      - USER_SERVICE_DB_URL=${USER_DB_URL}
      - USER_SERVICE_JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - USER_SERVICE_JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile.booking-service
    ports:
      - "8082:8082"
    environment:
      - BOOKING_SERVICE_ENV=production
      - BOOKING_SERVICE_DB_URL=${BOOKING_DB_URL}
      - BOOKING_SERVICE_JWT_ACCESSSECRET=${JWT_ACCESS_SECRET}
      - BOOKING_SERVICE_JWT_REFRESHSECRET=${JWT_REFRESH_SECRET}
      - USER_SERVICE_URL=http://user-service:8080
      - SALON_SERVICE_URL=http://salon-service:8081
    depends_on:
      - postgres
      - user-service
      - salon-service
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=salon
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
