apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: user-service
          imagePullPolicy: Always
          env:
            - name: USER_SERVICE_ENV
              value: prod
            - name: USER_SERVICE_LOG_LEVEL
              value: info
