apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  config.yaml: |
    env: prod
    server:
      port: "8080"
    db:
      url: "postgres://user:password@postgres:5432/salon_users?sslmode=disable"
    jwt:
      accesssecret: ""
      refreshsecret: ""
      accessttlminutes: 15
      refreshttldays: 7
    otp:
      expiryminutes: 5
    ratelimit:
      otprequestsperminute: 3
    log:
      level: "info"
      servicename: "user-service"
  # Observability environment variables for Prometheus, Grafana, Loki
  LOG_FORMAT: "json"
  LOG_LEVEL: "info"
  JAEGER_ENDPOINT: "http://jaeger.observability.svc.cluster.local:14268/api/traces"
  OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger.observability.svc.cluster.local:14268/api/traces"
  OTEL_SERVICE_NAME: "user-service"
