services:
  # User Service - Development
  - type: web
    name: user-service-dev
    runtime: docker
    plan: free
    branch: develop
    autoDeploy: true  # Auto-deploy for dev
    dockerfilePath: ./Dockerfile.user-service
    envVars:
      - key: PORT
        value: 8080
      - key: USER_SERVICE_ENV
        value: dev
      - key: USER_SERVICE_SERVER_PORT
        value: 8080
      - key: USER_SERVICE_DB_URL
        fromDatabase:
          name: salon-db-dev
          property: connectionString
      - key: USER_SERVICE_JWT_ACCESSSECRET
        sync: false
      - key: USER_SERVICE_JWT_REFRESHSECRET
        sync: false
      - key: USER_SERVICE_JWT_ACCESSTTLMINUTES
        value: 15
      - key: USER_SERVICE_JWT_REFRESHTTLDAYS
        value: 7
      - key: USER_SERVICE_OTP_EXPIRYMINUTES
        value: 5
      - key: USER_SERVICE_LOG_LEVEL
        value: debug
      - key: USER_SERVICE_LOG_SERVICENAME
        value: user-service-dev

  # Salon Service - Development
  - type: web
    name: salon-service-dev
    runtime: docker
    plan: free
    branch: develop
    autoDeploy: true  # Auto-deploy for dev
    dockerfilePath: ./Dockerfile.salon-service
    envVars:
      - key: PORT
        value: 8081
      - key: SALON_SERVICE_ENV
        value: dev
      - key: SALON_SERVICE_SERVER_PORT
        value: 8081
      - key: SALON_SERVICE_DB_URL
        fromDatabase:
          name: salon-db-dev
          property: connectionString
      - key: SALON_SERVICE_JWT_ACCESSSECRET
        sync: false
      - key: SALON_SERVICE_JWT_REFRESHSECRET
        sync: false
      - key: SALON_SERVICE_JWT_ACCESSTTLMINUTES
        value: 15
      - key: SALON_SERVICE_JWT_REFRESHTTLDAYS
        value: 7
      - key: SALON_SERVICE_OTP_EXPIRYMINUTES
        value: 5
      - key: SALON_SERVICE_LOG_LEVEL
        value: debug
      - key: SALON_SERVICE_LOG_SERVICENAME
        value: salon-service-dev

  # Booking Service - Development
  - type: web
    name: booking-service-dev
    runtime: docker
    plan: free
    branch: develop
    autoDeploy: true  # Auto-deploy for dev
    dockerfilePath: ./Dockerfile.booking-service
    envVars:
      - key: PORT
        value: 8082
      - key: BOOKING_SERVICE_ENV
        value: dev
      - key: BOOKING_SERVICE_SERVER_PORT
        value: 8082
      - key: BOOKING_SERVICE_DB_URL
        fromDatabase:
          name: salon-db-dev
          property: connectionString
      - key: BOOKING_SERVICE_JWT_ACCESSSECRET
        sync: false
      - key: BOOKING_SERVICE_JWT_REFRESHSECRET
        sync: false
      - key: BOOKING_SERVICE_JWT_ACCESSTTLMINUTES
        value: 15
      - key: BOOKING_SERVICE_JWT_REFRESHTTLDAYS
        value: 7
      - key: BOOKING_SERVICE_LOG_LEVEL
        value: debug
      - key: BOOKING_SERVICE_LOG_SERVICENAME
        value: booking-service-dev
      - key: USER_SERVICE_URL
        value: https://user-service-dev.onrender.com
      - key: SALON_SERVICE_URL
        value: https://salon-service-dev.onrender.com
      - key: PAYMENT_SERVICE_URL
        value: https://payment-service-dev.onrender.com
      - key: NOTIFICATION_SERVICE_URL
        value: https://notification-service-dev.onrender.com

  # Payment Service - Development
  - type: web
    name: payment-service-dev
    runtime: docker
    plan: free
    branch: develop
    autoDeploy: true  # Auto-deploy for dev
    dockerfilePath: ./Dockerfile.payment-service
    envVars:
      - key: PORT
        value: 8083
      - key: PAYMENT_SERVICE_ENV
        value: dev
      - key: PAYMENT_SERVICE_SERVER_PORT
        value: 8083
      - key: PAYMENT_SERVICE_DB_URL
        fromDatabase:
          name: salon-db-dev
          property: connectionString
      - key: PAYMENT_SERVICE_LOG_LEVEL
        value: debug
      - key: PAYMENT_SERVICE_LOG_SERVICENAME
        value: payment-service-dev
      - key: PAYMENT_SERVICE_STRIPE_SECRET_KEY
        sync: false
      - key: PAYMENT_SERVICE_STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYMENT_SERVICE_RAZORPAY_KEY_ID
        sync: false
      - key: PAYMENT_SERVICE_RAZORPAY_KEY_SECRET
        sync: false
      - key: PAYMENT_SERVICE_RAZORPAY_WEBHOOK_SECRET
        sync: false

  # Notification Service - Development
  - type: web
    name: notification-service-dev
    runtime: docker
    plan: free
    branch: develop
    autoDeploy: true  # Auto-deploy for dev
    dockerfilePath: ./Dockerfile.notification-service
    envVars:
      - key: PORT
        value: 8084
      - key: NOTIFICATION_SERVICE_ENV
        value: dev
      - key: NOTIFICATION_SERVICE_SERVER_PORT
        value: 8084
      - key: NOTIFICATION_SERVICE_DB_URL
        fromDatabase:
          name: salon-db-dev
          property: connectionString
      - key: NOTIFICATION_SERVICE_LOG_LEVEL
        value: debug
      - key: NOTIFICATION_SERVICE_LOG_SERVICENAME
        value: notification-service-dev
      - key: NOTIFICATION_SERVICE_SMTP_HOST
        sync: false
      - key: NOTIFICATION_SERVICE_SMTP_PORT
        value: 587
      - key: NOTIFICATION_SERVICE_SMTP_USERNAME
        sync: false
      - key: NOTIFICATION_SERVICE_SMTP_PASSWORD
        sync: false
      - key: NOTIFICATION_SERVICE_SMTP_FROM
        value: noreply@salon-dev.com
      - key: NOTIFICATION_SERVICE_TWILIO_ACCOUNT_SID
        sync: false
      - key: NOTIFICATION_SERVICE_TWILIO_AUTH_TOKEN
        sync: false
      - key: NOTIFICATION_SERVICE_TWILIO_FROM
        sync: false
      - key: NOTIFICATION_SERVICE_FCM_SERVER_KEY
        sync: false
      - key: NOTIFICATION_SERVICE_FCM_PROJECT_ID
        sync: false

databases:
  - name: salon-db-dev
    plan: free
    databaseName: salon_dev
    user: salon_user_dev
