env: dev
server:
  port: "8081"
db:
  url: "postgres://user:password@localhost:5432/salon?sslmode=disable"
jwt:
  accesssecret: "dev-access-secret-change-me"
  refreshsecret: "dev-refresh-secret-change-me"
  accessttlminutes: 60  # Longer for development
  refreshttldays: 30    # Longer for development
otp:
  expiryminutes: 10     # Longer for testing
log:
  level: debug
  servicename: salon-service-dev
