env: prod
server:
  port: "8083"
db:
  url: "postgres://user:password@prod-db.example.com:5432/salon_prod?sslmode=require"
log:
  level: warn  # Minimal logging for production
  servicename: payment-service-prod
payment:
  gateways:
    stripe:
      secretkey: ""  # Set via environment variables
      webhooksecret: ""  # Set via environment variables
      publickey: ""  # Set via environment variables
    razorpay:
      keyid: ""  # Set via environment variables
      keysecret: ""  # Set via environment variables
      webhooksecret: ""  # Set via environment variables
  webhook:
    timeout: 30s
    retries: 3
  idempotency:
    ttl: 24h
redis:
  url: "redis://prod-redis.example.com:6379/0"
  timeout: 5s
  maxretries: 3
ratelimit:
  requestsperminute: 100
  burstsize: 5  # Stricter for production
security:
  cors:
    enabled: true
    origins: ["https://salon.example.com"]
  webhook:
    verifysignature: true
