apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dev
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        logging: enabled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never  # Use locally built image
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: USER_SERVICE_DB_URL
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: DATABASE_URL
        - name: USER_SERVICE_JWT_ACCESSSECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_SECRET
        - name: USER_SERVICE_JWT_REFRESHSECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_REFRESH_SECRET
        # Jaeger tracing configuration
        - name: JAEGER_ENDPOINT
          value: "http://jaeger.observability.svc.cluster.local:14268/api/traces"
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger.observability.svc.cluster.local:14268/api/traces"
        - name: OTEL_SERVICE_NAME
          value: "user-service"
        # Structured logging for Loki
        - name: LOG_FORMAT
          value: "json"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dev
  labels:
    app: user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
