env: dev
server:
  port: "8081"
db:
  url: "postgres://user:password@localhost:5432/salon?sslmode=disable"
jwt:
  accesssecret: "dev-access-secret-change-me"
  refreshsecret: "dev-refresh-secret-change-me"
  accessttlminutes: 15
  refreshttldays: 7
otp:
  expiryminutes: 5
log:
  level: info
  servicename: salon-service
