env: dev
server:
  port: "8080"
db:
  url: "postgres://user:password@localhost:5432/salon_users?sslmode=disable"
jwt:
  accesssecret: "dev-access-secret-change-me"
  refreshsecret: "dev-refresh-secret-change-me"
  accessttlminutes: 15
  refreshttldays: 7
otp:
  expiryminutes: 5
ratelimit:
  otprequestsperminute: 3
log:
  level: "info"
  servicename: "user-service"
