apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: user-service
          imagePullPolicy: IfNotPresent
          env:
            - name: USER_SERVICE_ENV
              value: stage
            - name: USER_SERVICE_LOG_LEVEL
              value: info
