server:
  port: 8084
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: salon
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

logging:
  level: info
  format: json

notification:
  providers:
    email:
      smtp:
        enabled: true
        host: ""
        port: 587
        username: ""
        password: ""
        from: "noreply@salon.com"
        tls: true
      
      sendgrid:
        enabled: false
        api_key: ""
        from: "noreply@salon.com"
    
    sms:
      twilio:
        enabled: false
        account_sid: ""
        auth_token: ""
        from: ""
      
      aws_sns:
        enabled: false
        region: "us-east-1"
        access_key: ""
        secret_key: ""
    
    push:
      fcm:
        enabled: false
        server_key: ""
        project_id: ""
  
  queue:
    type: "memory" # memory, redis, rabbitmq
    redis:
      host: "localhost"
      port: 6379
      password: ""
      db: 0
    rabbitmq:
      url: "amqp://guest:guest@localhost:5672/"
      exchange: "notifications"
      queue: "notification_queue"
  
  retry:
    max_attempts: 3
    initial_delay: 1s
    max_delay: 30s
    backoff_multiplier: 2.0
  
  rate_limit:
    per_recipient_per_hour: 50
    per_type_per_hour: 1000

security:
  rate_limit:
    requests_per_minute: 200
    burst: 50
  
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true

monitoring:
  metrics:
    enabled: true
    path: "/metrics"
  
  health:
    path: "/health"
    ready_path: "/ready"
