server:
  port: 8082
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: salon
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

logging:
  level: info
  format: json

payment:
  gateways:
    stripe:
      enabled: true
      secret_key: ""
      webhook_secret: ""
      api_version: "2023-10-16"
    razorpay:
      enabled: true
      key_id: ""
      key_secret: ""
      webhook_secret: ""
  
  default_currency: "INR"
  timeout: 30s
  retry_attempts: 3
  
  webhook:
    timeout: 10s
    max_body_size: 1048576 # 1MB

security:
  rate_limit:
    requests_per_minute: 100
    burst: 20
  
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true

monitoring:
  metrics:
    enabled: true
    path: "/metrics"
  
  health:
    path: "/health"
    ready_path: "/ready"
